version: "3.8"
services:
  nginx:
    image: nginx
    environment:
      - NGINX_PORT=80
    volumes:
      - ./public/:/usr/share/nginx/html/
      - ./templates/:/etc/nginx/templates/
    ports:
      - 8082:80
  server:
    build: .
    environment:
      PORT: 80
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
